### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-mpi#21]
Any objections to a bugfix release?

**Comment by kmpaul** [comment]
No objections at all.  I'll get started on that now.

**Comment by kmpaul** [comment]
Version 1.0.2 is now up on PyPI, and the PRs to the feedstock have been merged.  But I still can't find version 1.0.2 on conda, yet.

**Comment by kmpaul** [comment]
Done!  Version 1.0.2 is now on PyPI and conda-forge.
