### ISSUE TITLE
Resilience in dask-mpi

### ISSUE THREAD

**Issue by CarlosCuetoM** [dask/dask-mpi#31]
Hi!

I've been reading through the docs, but I'm still a bit unsure about whether the resilience/fault tolerance in dask-distributed in maintained in dask-mpi. 

As I understood it, MPI is only used to discover nodes and not for communication, but would the fact that the execution has been launched with MPI in the first place imply that it will collapse in case a node fails?

Carlos

**Comment by willirath** [comment]
I guess that a worker which dies and takes its MPI process with it will bring down the MPI cluster. A simple test would be to submit something that terminates the worker it's living on:

```python
def kill_my_worker_process():
    os.kill(os.getpid(), 15)
```

But you'll probably be able to handle problems caught by the nanny processes (like exceeding memory limits).

**Comment by CarlosCuetoM** [comment]
Yes, that seems to bring down the whole MPI cluster.

Thanks!
