### ISSUE TITLE
Version number for next release

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-mpi#39]
Hi All, 

As part of an upcoming release I would like to release dask-mpi.  What should the version number be?  Some options:

1.  `1.1` - a moderate bump from the current version
3.  `2.2` - let's just match Dask version numbers going forward

What should we use?

**Comment by andersy005** [comment]
+1 for `2.2`

**Comment by jrbourbeau** [comment]
Closing as it looks like we went with `2.0`
