### ISSUE TITLE
Can the scheduler info be broadcast at startup instead of using scheduler file?

### ISSUE THREAD

**Issue by rcthomas** [dask/dask-mpi#45]
If I hit the end of a job allocation, or I OOM my cluster, or the cluster is shut down abruptly, an old scheduler.json file can be found by the workers on my next try.  I could always be sure to delete this file before I launch `dask-mpi` but why not just pass the info over the wire?

Sound handy?  We'd probably get PR that in before I figured out my other MPI cluster question...

**Comment by mrocklin** [comment]
I think that using MPI to bootstrap this sort of information sounds like a
good idea.

**Comment by kmpaul** [comment]
@rcthomas This is what is done in Dask-MPI.  The scheduler is started, the address is broadcast to the workers.

**Comment by kmpaul** [comment]
@rcthomas Look here:

https://github.com/dask/dask-mpi/blob/de00068c22d735fca6a1aa561fc176f99ac3385d/dask_mpi/core.py#L57-L75

**Comment by rcthomas** [comment]
Thanks, I inferred something from the behavior I was seeing that actually looking at the code would have made obvious.  OK.  So something's wrong with what I'm doing; we'll investigate further as to how this is happening.
