### ISSUE TITLE
Multiple schedulers no workers

### ISSUE THREAD

**Issue by KevinSayers** [dask/dask-mpi#49]
I am interested in using dask-mpi on our cluster. Whenever I launch Dask I seem to only be getting multiple schedulers and no workers. My understanding was that rank 0 should be the scheduler and the others should be workers. 

dask-mpi
```python 
from dask_mpi import initialize
from dask.distributed import Client, wait

initialize()
client = Client()
```

sbatch:
```
#!/bin/bash 
#SBATCH --nodes=2
#SBATCH --time=01:00:00
#SBATCH --partition=debug

module purge
ml intel-mpi/2018.0.3 
mpirun -np 4 dask-mpi --scheduler-file scheduler.json --interface ib0
```

slurm output:
```
distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO -   Scheduler at:   tcp://10.148.2.31:39065
distributed.scheduler - INFO -   Scheduler at:   tcp://10.148.2.31:45246
distributed.scheduler - INFO -   Scheduler at:   tcp://10.148.2.31:43614
distributed.scheduler - INFO -   Scheduler at:   tcp://10.148.2.31:43968
```

In the `scheduler.json` I see one of these listed as the scheduler, and no entries in the workers field. Am I missing something necessary in the setup or if this may be a site specific issue?

**Comment by kmpaul** [comment]
@KevinSayers It looks like you might be mixing up the 2 different modes of operation.  It looks like you are *both* running `dask-mpi` from the command line (i.e., the `mpirun -np 4 dask-mpi --scheduler-file scheduler.json --interface ib0` line in your sbatch file) *and* from within the script (with the `initialize` function).  The 2 different modes of operation do not go together; you should run *either* from within the script *or* from the command line.

Can you tell me how you are *launching* your script and/or dask?  What are you executing on the command-line?

...Some backstory:

### Command-Line Usage:

If you run `dask-mpi` from the command-line, it will create your scheduler on Rank 0 and your workers on Ranks 1-3.  To do this, you would simply run:

```bash
mpirun -np 4 dask-mpi --scheduler-file scheduler.json --interface ib0
```

This will create your dask scheduler and workers.  In your Jupyter Notebook (or your script), you will need to connect to the scheduler you created *explicitly* with:

```python
from dask.distributed import Client

client = Client(f'{address}:{port}')
```

where `address` and `port` are your scheduler's address and port.  And if you were running a script called `myscript.py`, you would run your script simply with:

```bash
python myscript.py
```

(NOTE: No use of `mpirun`!)

### In-Script Usage:

You can also create your scheduler and workers *from within the script*, and then they will automatically be torn down when your script finishes execution.  To do you, you would *not* use the `dask-mpi` command.  Instead, you would create your script like you did above:

```python
from dask_mpi import initialize
from dask.distributed import Client, wait

initialize()
client = Client()
```

And then you would execute that script with `mpirun` like so:

```bash
mpirun -np 4 --scheduler-file scheduler.json --interface ib0 python myscript.py
```

When the script gets to the `initialize` call in your script, it will create the scheduler (on Rank 0) and the workers (on Ranks 2-3) and then run the script (on Rank 1).  When the script has finished executing, the scheduler and workers will be taken down.

**Comment by KevinSayers** [comment]
@kmpaul thanks for the feedback

## Command-Line Usage

Running the cli as suggested, I still seem to get 4 schedulers starting. 
```
$ ml intel-mpi/2018.0.3 
$ mpirun -np 4 dask-mpi --scheduler-file scheduler.json --interface ib0
distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO -   Scheduler at:  tcp://10.148.0.110:40792
distributed.scheduler - INFO -   Scheduler at:  tcp://10.148.0.110:43076
distributed.scheduler - INFO -   Scheduler at:  tcp://10.148.0.110:42459
distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO -   Scheduler at:  tcp://10.148.0.110:36906
```

Specifying the scheduler in a dummy python script. 
```python

# daskmpitest.py
from dask_mpi import initialize
from distributed import Client
import time
import socket
from collections import Counter

client = Client('10.148.0.110:36906')

def test():
   return socket.gethostname()

result = []
for i in range(0,5):
   result.append(client.submit(test).result())
print (Counter(result))

```

When I run: `python daskmpitest.py` it just waits, presumably because there are no workers. 

If I then make a worker manually `dask-worker 10.148.0.110:36906 --no-nanny --interface ib0` the script runs fine.

**Comment by kmpaul** [comment]
@KevinSayers So, it looks like `rank == 0` in all of the processes created by `mpirun`.  I've seen this problem before, and I'm trying to remember why this happens...

**Comment by kmpaul** [comment]
You might look at this:

https://wiki.mpich.org/mpich/index.php/Frequently_Asked_Questions#Q:_All_my_processes_get_rank_0.

**Comment by kmpaul** [comment]
@KevinSayers Do you install `dask-mpi` with conda?

**Comment by kmpaul** [comment]
From the information on the link above, it sounds like this can be an issue when you have 2 different mpi versions available.  It looks like you have a version of MPI installed on the system (i.e., `ml intel-mpi/2018.0.3`).  You might be installing a different version of MPI with `dask-mpi` when you install it.  If so, I think these two versions of MPI are incompatible.

**Comment by KevinSayers** [comment]
@kmpaul that seems to have been it. If I install via pip both the cli and the in-script work. Thank you again for all your help!

**Comment by kmpaul** [comment]
Yes!  I was going to suggest that.  I think that the conda `dask-mpi` package requires `mpi4py`...and the `mpi4py` package will install `mpi` if it hasn't been installed in your conda environment already.

Installing everything with pip, on the other hand, should actually build `mpi4py` against the version of the MPI found on the system.  So, I'm very glad that works!
