### ISSUE TITLE
Migrate CI to GitHub Actions?

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/dask-mpi#54]
Due to changes in the Travis CI billing, the Dask org is migrating Travis CI to GitHub Actions.

This repo appears to use CircleCI. As we are putting in the effort to migrate many projects to GitHub Actions does it make sense to standardise here?

See dask/community#107 for more details.

**Comment by kmpaul** [comment]
Hey, @jacobtomlinson!  Yeah.  I think it makes sense to standardize.  I'll put that as a to-do task for myself this week.

**Comment by jacobtomlinson** [comment]
Thanks Kevin! Also hey! It's been a while.

**Comment by kmpaul** [comment]
It *has* been a while!  It's nice to see your face...even if it's just a little icon.  😄

**Comment by jacobtomlinson** [comment]
Closed in #55
