### ISSUE TITLE
Include batch job full example in docs?

### ISSUE THREAD

**Issue by rsignell-usgs** [dask/dask-mpi#60]
I'm struggling a bit to get my first batch job with dask-mpi going, and I think it would be helpful to have a full minimal example (if possible) added to the docs.  

I'm wondering specifically two things:

1.  How to specify my custom conda environment in my job control script.  Just doing `source activate pangeo`  as in the job control script below doesn't seem to work.
2.  Do I need to have to wrap my `test-mpi.py` code in a `main()` function for dask-mpi to work?

My job script looks like this:
```
#!/bin/bash
#SBATCH -p compute
#SBATCH -A science
#SBATCH --mem=144G
#SBATCH -t 01:00:00

#SBATCH --nodes=2                     # Number of nodes
#SBATCH --ntasks-per-node=36

echo "Running Dask-MPI"
module openmpi/intel/4.0.1
source activate pangeo
mpirun -np 72 python /vortexfs1/usgs/rsignell/HRRR/HRRR-s3-download-mpi.py
 ```

**Comment by kmpaul** [comment]
Hey, @rsignell-usgs!  What does your `HRRR-s3-download-mpi.py` script look like?

**Comment by kmpaul** [comment]
Also, what machine are you trying to run on?  What you need to do in your job submission script to activate your conda environment can vary from machine to machine, depending on how the sysadmins set the machine up.  Some machines do not make a copy of the bash environment (i.e., environment variables, etc.) on the compute nodes, so when you try to run the script on the compute nodes, it doesn't run as you would expect on the login node.

**Comment by kmpaul** [comment]
...Incidentally, this is the reason why I didn't document the full process for launching `dask-mpi` in batch mode.  It varies so much from machine to machine that one (or even three) examples might actually lead people to more confusion.  But perhaps more documentation could help, nonetheless.

**Comment by andersy005** [comment]
> How to specify my custom conda environment in my job control script. Just doing source activate pangeo as in the job control script below doesn't seem to work.

@rsignell-usgs, does the `source activate` step work if you replace 

`#!/bin/bash` with `#!/bin/bash -l`

?

**Comment by rsignell-usgs** [comment]
Adding the `#!/bin/bash -l` indeed let my script find my environment and then I just needed to clean up the `.py` file that I created using `nbconvert`.   I had left a `%%time` in there, which got translated into something goofy.  So when I removed that, it worked!

@andersy005 and @kmpaul, thanks for the help!

**Comment by kmpaul** [comment]
@rsignell-usgs!  Awesome!  I'm glad it works.  Thanks for reaching out!

Thanks, @andersy005, for the actual solution.  😄
