### ISSUE TITLE
Disable/remove CircleCI checks?

### ISSUE THREAD

**Issue by kmpaul** [dask/dask-mpi#62]
I have done everything that I can do without administrative privileges on this repository to remove the CircleCI checks.  All testing has been moved to GitHub Actions (which appear to be working) and I have removed the `.circleci` directory from the repository.  I have unfollowed the project on CircleCI...but the CircleCI checks still show up in new PRs and pushes to the `master` branch.  Is this because of a branch protection rule?

If anyone else can fix this, I would greatly appreciate it.

Thanks!

**Comment by andersy005** [comment]
> Is this because of a branch protection rule?

It's likely due to an active webhook. One solution is to delete the CircleCI webhook from the repository settings.

**Comment by kmpaul** [comment]
Again, I don't have admin privileges to do that, though.

**Comment by andersy005** [comment]
> Again, I don't have admin privileges to do that, though.
> If anyone else can fix this, I would greatly appreciate it.

Cc @dask/maintenance :)

**Comment by jrbourbeau** [comment]
I'll go ahead and delete the webhook

**Comment by jrbourbeau** [comment]
Opened up a PR over at https://github.com/dask/dask-mpi/pull/63 to double check that deleting the webhook removes the CircleCI check. Looks like that did the trick

**Comment by kmpaul** [comment]
Thank you!
