### ISSUE TITLE
Enable CircleCI testing

### ISSUE THREAD

**Issue by kmpaul** [dask/dask-mpi#7]
I have a `.circleci/config.yml` file in place, but this should be reviewed before deployment.

Also, we might need the recent changes to `dask/distributed` to be released before we enable CI.

**Comment by kmpaul** [comment]
Should I use TravisCI, instead?  The rest of the Dask projects seem to use Travis.  I’m happy to use Travis. It doesn’t matter to me.

**Comment by kmpaul** [comment]
Circle it is, then!

**Comment by kmpaul** [comment]
@mrocklin Can you add the dask-mpi project to CircleCI?  Only the project admin can do it.

**Comment by mrocklin** [comment]
I think that this is done.  https://circleci.com/gh/dask/workflows/dask-mpi

**Comment by mrocklin** [comment]
(though I'm not super familiar here, and so could be wrong)
