### ISSUE TITLE
Scheduler port number cannot be assigned on the CLI

### ISSUE THREAD

**Issue by mahendrapaipuri** [dask/dask-mpi#72]
`mpirun -np 4 --map-by node dask-mpi --no-nanny --nthreads=1 --memory-limit=0 --scheduler-file=scheduler_file.json --interface=ib0 --scheduler-port=8786 &`

**What happened**:
I am a newbie to dask and I found `dask-mpi` very portable approach to setup dask cluster on multiple platforms. I have noticed that there is a CLI option to specify the scheduler port number using `--scheduler-port` but when I use it (example usage is given above) it does not use this port and always generate random port numbers, which is the default option.

**What you expected to happen**:
I suppose that my scheduler should be at the port `8786` in the above example. It would be nice to have this functionality for us.

**Anything else we need to know?**:
There was this [PR](https://github.com/dask/dask-mpi/pull/51) to fix this issue, but it was closed without merging into the master.

**Environment**:

- Dask version: 2021.7.1
- Python version: 3.7.10
- Operating System: CentOS Linux release 7.9.2009 
- Install method (conda, pip, source): pip

**Comment by jacobtomlinson** [comment]
It looks like the scheduler port stopped being passed to the `Scheduler` object in #46. But the flag still exists.

@kmpaul do you know if this was removed intentionally?

**Comment by kmpaul** [comment]
It wasn't removed intentionally. I think it was missed.

**Comment by mahendrapaipuri** [comment]
@kmpaul @jacobtomlinson Thanks for the replies. So, I assume it is pretty trivial to add this flag to `Scheduler`. 

I have one more question, if I may ask it here! In the documentation, you clearly mention that `--nanny` flag works only for some MPI implementations because of process forking. As far as I know, OpenMPI implementations with verbs support complains about process forking. But, OpenMPI with UCX support do not have this problem, it is quite happy to allow process forking. We have few MPI codes that do this and we did not find any problems with OpenMPI+UCX. Unfortunately, `dask-mpi` with `--nanny` flags still fails with this OpenMPI+UCX implementation. Are there any MPI implementations that you have tested will work for this setting? Thanks

**Comment by jacobtomlinson** [comment]
I've opened #73 to fix the scheduler port issue and I've opened #74 to cover your additional question about process forking on OpenMPI+UCX.

**Comment by kmpaul** [comment]
@mahendrapaipuri:  I commented on your question in #74.
