### ISSUE TITLE
Nanny fails on OpenMPI+UCX

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/dask-mpi#74]
In the documentation, you clearly mention that `--nanny` flag works only for some MPI implementations because of process forking. As far as I know, OpenMPI implementations with verbs support complains about process forking. But, OpenMPI with UCX support do not have this problem, it is quite happy to allow process forking. We have few MPI codes that do this and we did not find any problems with OpenMPI+UCX. Unfortunately, `dask-mpi` with `--nanny` flags still fails with this OpenMPI+UCX implementation. Are there any MPI implementations that you have tested will work for this setting? Thanks

_Originally posted by @mahendrapaipuri in https://github.com/dask/dask-mpi/issues/72#issuecomment-890117924_

**Comment by kmpaul** [comment]
Hey, @jacobtomlinson:  I only tested OpenMPI (without UCX) and MPICH.  With the old version of MPICH, I was able to get the `--nanny` option to work, I think.  But maybe things have changed and it doesn't work with any flavor of MPI.  I probably need to make time to test across the spectrum of packages.  I always felt that just testing against MPICH and OpenMPI would be enough.

**Comment by kmpaul** [comment]
@mahendrapaipuri @jacobtomlinson:  It's unclear to me if this issue has been addressed with the recent bugfix #77 as well as the recent PR merges (#73 and #75).  @mahendrapaipuri, are you able to test with the `main` branch straight from GitHub?

**Comment by mahendrapaipuri** [comment]
@kmpaul Well, I finally managed to test the PR. So, I used the `main` branch from the GitHub and `dask-mpi` worked without any issues both on "toy" and "application" problems. I tested with both OpenMPI 4.1.1 + UCX and OpenMPI 3.1.3 + verbs and in both cases it worked. With OpenMPI 3.1.3 + verbs support, OpenMPI threw me some warnings about processing forking though (which is normal). Seems like these PRs fixed most of the problems we had before. I think if you could update the documentation as well, that would be really helpful! 

Thanks @kmpaul for fixing the bugs!

**Comment by mahendrapaipuri** [comment]
@kmpaul @jacobtomlinson When do you plan to have next release with these bug fixes? Thanks!

**Comment by kmpaul** [comment]
Well, good question.  Looking at my schedule, I think I can have something out in a week.

**Comment by jacobtomlinson** [comment]
@kmpaul I'd be happy to sync up while you do it so that I know the procedure too and could possibly do releases in the future if you don't have time.

**Comment by kmpaul** [comment]
@jacobtomlinson:  Thank you!  I'd love to share the responsibility.  

I believe that dask-mpi's release procedure is sadly out of date.  I think the last release I did was manual.  Currently, all of the tests are passing, and so I'm comfortable triggering a new PyPI release and then trigger a conda-forge build (manually).  However, I'd like to automate this process a little better.  Here's what I see needed to be put in place:

- [ ] Enable the GHA procedure for creating a new PyPI release triggered on a new GitHub release
- [ ] Can GHA be used to automatically trigger a new conda-forge build? (e.g., [pushing to the regro-cf-autotick-bot branch](https://conda-forge.org/docs/maintainer/updating_pkgs.html#pushing-to-regro-cf-autotick-bot-branch)
  - If yes, let's do that!
  - If no, ...that sucks!

Is this satisfactory?

**Comment by jacobtomlinson** [comment]
Yeah that sounds great. Check out `dask-cloudprovider` for an example of doing exactly this. 

GHA pushes to PyPI on tags. That PyPI build triggers conda forge. 

Happy to sync up and go through it any time if you prefer. https://jacobtomlinson.dev/calendar

**Comment by kmpaul** [comment]
:+1000:  (Guess that's not a thing...)

Yes.  I'll take a look at `dask-cloudprovider` and try to reproduce the logic for `dask-mpi`.

**Comment by kmpaul** [comment]
...and my calender sucks at the moment, but if I need to chat, I'll sync up with your calendar.  Thanks!

**Comment by kmpaul** [comment]
@mahendrapaipuri:  We now have a new release on PyPI!  Sorry for the ***LONG*** delay on that.  (We now have a better release process, too.)

**Comment by kmpaul** [comment]
We are still working on the conda-forge release.  So, keep watching for updates on that.

**Comment by mahendrapaipuri** [comment]
@kmpaul Thanks a lot! Thats perfect timing as I am planning a demo to my team next week.

**Comment by kmpaul** [comment]
@mahendrapaipuri:  Excellent!  Happy to (*finally*) help!
